name: docs

on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, repoened, edited]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - name: Setup Graphviz environment
      run: |
        sudo apt-get install graphviz

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
      
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        key: ${{ runner.os }}-pip-${{ hashFiles('./requirements/requirements.txt') }}-${{ hashFiles('**/docs.txt') }}-${{ hashFiles('**/test.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r ./requirements/requirements.txt
        pip install -r ./requirements/docs.txt
        pip install -r ./requirements/test.txt
        pip install -r ./requirements/test.txt

    - name: Generate project dependency graphs
      run: |
        pyreverse --ignore="tests" -o png -p telereddit telereddit
        mv classes_telereddit.png docs/images/classes_telereddit.png
        mv packages_telereddit.png docs/images/packages_telereddit.png
        
    - name: Generate documentation
      run: |
        rm -rf docs/telereddit
        pdoc --html --output-dir="docs/" --template-dir="docs/templates" --config show_source_code=False --force .
      env:
        REDDIT_BOTS_MACHINE: GITHUB

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        # Artifact name
        name: gh-pages
        # Path of the directory containing the static assets.
        path: docs/telereddit
        # Duration after which artifact will expire in days.
        # retention-days: # optional, default is 1

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v2.0.0
      with:
        # Should this action only emit build telemetry instead of deploying the build artifact?
        # emit_telemetry: # optional, default is false
        # The status of the previous build.
        # conclusion: # optional
        # GitHub token
        # token: # default is ${{ github.token }}
        # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
        # timeout: # optional, default is 600000
        # Maximum number of status report errors before cancelling a deployment (default: 10)
        # error_count: # optional, default is 10
        # Time in milliseconds between two deployment status report (default: 5 seconds)
        # reporting_interval: # optional, default is 5000
        # Name of the artifact to deploy
        artifact_name: gh-pages
        # Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)
        # preview: # optional, default is false

#    - name: Deploy docs to Github Pages
#      uses: JamesIves/github-pages-deploy-action@releases/v3
#      with:
#        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#        BRANCH: gh-pages
#        FOLDER: docs/telereddit
